In [ ]:
def containsduplicate(nums):
    seen = set()

    for num in nums:
        if num in seen:
            return True
        seen.add(num)

    return False




print(containsduplicate([1,2,3,2])) # True
print(containsduplicate([1,2,3,4])) # False

True
False

In [27]:
def longestsubstringwithoutrepeatingcharacters(s):
    left, right = 0, 0
    unique_number = set()
    max_length = 0

    for right in range(len(s)):
        while s[right] in unique_number:
            unique_number.remove(s[left])
            left += 1

        unique_number.add(s[right])
        max_length = max(max_length, right - left + 1)
    
    return max_length



    

print(longestsubstringwithoutrepeatingcharacters("abcabcbb")) # 3
print(longestsubstringwithoutrepeatingcharacters("bbbbb")) # 1
print(longestsubstringwithoutrepeatingcharacters("pwwkew")) # 3

3
1
3

In [147]:
def mergesortedarray(nums1, m, nums2, n):
    i = m - 1
    j = n - 1
    k = m + n - 1

    while j >= 0:
        if nums1[i] > nums2[j] and i >= 0:
            nums1[k] = nums1[i]
            i -= 1
        else:
            nums1[k] = nums2[j]
            j -= 1

        k -= 1

    return nums1



print(mergesortedarray([1,2,3,0,0,0], 3, [2,5,6], 3))

[1, 2, 2, 3, 5, 6]

In [36]:
def validparentheses(s):
    stack = []
    mapping = {')':'(', '}':'{', ']':'['}

    for char in s:
        if char in mapping.values():
            stack.append(char)
        elif char in mapping:
            if not stack or stack[-1] != mapping[char]:
                return False
            stack.pop()

    return not stack
            
            



print(validparentheses("()[]{}"))
print(validparentheses("(]"))
print(validparentheses("([{}])"))

True
False
True

In [37]:
def searchinsertposition(nums, target):
    left, right = 0, len(nums) - 1

    while left <= right:
        mid = (left + right) // 2
        if nums[mid] == target:
            return mid 
        elif nums[mid] > target:
            right = mid - 1
        else:
            left = mid + 1

    return left
            
            



print(searchinsertposition([1,3,5,6], 5))
print(searchinsertposition([1,3,5,6], 2))
print(searchinsertposition([1,3,5,6], 7))

2
1
4

In [146]:
def topkfrequentelements(nums, k):
    hashmap = {}

    for num in nums:
        if num in hashmap:
            hashmap[num] += 1
        else: 
            hashmap[num] = 1

    hashmap_sorted = dict(sorted(hashmap.items(), key=lambda iter_ : iter_[1], reverse=True))

    result = []

    for key, value in hashmap_sorted.items():
        result.append(key)

    return result[:k]
            
            
print(topkfrequentelements([1,1,1,2,2,3], 2))

[1, 2]

transactions
------------
user_id
transaction_id
amount
transaction_time
status

Задача 1 — GROUP BY

Найти сумму транзакций по каждому пользователю.

Ожидаемые поля:

In [ ]:
SELECT user_id, SUM(amount) as total_amount
FROM transactions
GROUP BY user_id

SyntaxError: invalid syntax (2797458918.py, line 1)

In [75]:
import pandas as pd

df = pd.DataFrame({
    'user_id': [1,1,2,2,3],
    'amount': [100,200,150,300,50],
    'transaction_date': [
        '2025-01-01',
        '2025-01-05',
        '2025-01-03',
        '2025-01-10',
        '2025-01-02'
    ]
})

data = df.copy()

ad = data.groupby('user_id')['amount'].agg(['count', 'mean', 'sum'])
ad.columns = ['transaction_count', 'avg_amount', 'max_amount']

display(ad)

         transaction_count  avg_amount  max_amount
user_id
1                        2       150.0         300
2                        2       225.0         450
3                        1        50.0          50

In [83]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

a = arr.sum(axis=1)
b = arr.sum(axis=0)

In [84]:
a

array([ 6, 15])

In [85]:
b

array([5, 7, 9])

In [90]:
arr.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

In [86]:
normalize = (arr - arr.mean()) / arr.std()

In [87]:
normalize

array([[-1.46385011, -0.87831007, -0.29277002],
       [ 0.29277002,  0.87831007,  1.46385011]])

In [92]:
df = pd.DataFrame({
    'user_id': [1,1,2,2,2],
    'amount': [100,200,50,70,80],
    'date': pd.to_datetime([
        '2025-01-01',
        '2025-01-03',
        '2025-01-01',
        '2025-01-05',
        '2025-01-10'
    ])
})

In [93]:
df

   user_id  amount       date
0        1     100 2025-01-01
1        1     200 2025-01-03
2        2      50 2025-01-01
3        2      70 2025-01-05
4        2      80 2025-01-10

In [99]:
global_max_date = df['date'].max()

result = df.groupby('user_id').agg(
    total_amount=('amount', 'sum'), 
    avg_amount=('amount', 'mean'),
    count_transaction=('amount', 'count'),
    last_transaction_date=('date', 'max')).reset_index()


result['days_since_last_transaction'] = (global_max_date - result['last_transaction_date']).dt.days

In [100]:
result

,user_id,total_amount,avg_amount,count_transaction,last_transaction_date,days_since_last_transaction
0,1,300,150.000000,2,2025-01-03,7
1,2,200,66.666667,3,2025-01-10,0

In [105]:
def search(nums):
    hashmap = {}

    for num in nums:
        if num in hashmap:
            hashmap[num] += 1
        else:
            hashmap[num] = 1

    limit = len(nums) // 2

    for key, value in hashmap.items():
        if value > limit:
            return key

    return []

search([2,2,1,1,1,2,2])

2

In [118]:
def search(nums):
    if len(nums) == 0:
        return 0
    
    nums.sort()

    longest = 1
    current = 1

    for i in range(1, len(nums)):
        if nums[i] == nums[i - 1]:
            continue
            
        elif nums[i] == nums[i - 1] + 1:
            current += 1

        else:
            longest = max(longest, current)
            current = 1

    return longest

search([100,4,200,1,3,2])

4

In [ ]:
def search(nums):
    nums_set = set(nums)

    longest = 0

    for num in nums_set:
        if num - 1 not in nums_set:
            current_num = num 
            current_streak = 1

            while current_num + 1 in nums_set:
                current_num += 1 
                current_streak += 1

            longest = max(longest, current_streak)

    return longest

search([100,4,200,1,3,2])

4

In [1]:
import re

In [4]:
text = "1 стакан молока"

find_text = re.sub(r'^[0-9]', '', text)

In [ ]:
from pydantic import BaseModel

class IngredientInput(BaseModel):
    ingredient_text: str


class ParsedIngredient(BaseModel):
    ingredient: str
    quantity: float
    unit: str


import re

UNIT_MAP = {
    "стакан": 200,  # ml
    "л": 1000,
    "мл": 1
}

from transformers import pipeline

ner_model = pipeline("token-classification", model="bert-base-cased")


def extract_with_ner(text: str):
    entities = ner_model(text)

    ingredient = None
    quantity = None
    unit = None

    for e in entities:
        if e["entity"] == "QUANTITY":
            quantity = float(e["word"])
        elif e["entity"] == "UNIT":
            unit = e["word"]
        elif e["entity"] == "FOOD":
            ingredient = e["word"]

    return {
        "ingredient": ingredient,
        "quantity": quantity,
        "unit": unit
    }

def normalize(parsed: dict):
    unit = parsed["unit"]
    quantity = parsed["quantity"]

    if unit in UNIT_MAP:
        return {
            "ingredient": parsed["ingredient"],
            "quantity": quantity * UNIT_MAP[unit],  # ✅ остаётся quantity
            "unit": "ml"
        }

    return parsed

def process_ingredient(text: str):
    # 1. extraction (regex or ML)
    parsed = extract_with_ner(text)

    # 2. normalization
    normalized = normalize(parsed)

    return ParsedIngredient(**normalized)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: bert-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [14]:
parsed = extract_with_regex("1 стакан молока")

In [12]:
parsed

{'quantity': 1, 'unit': 'стакан', 'ingredient': 'молока'}

In [15]:
result = process_ingredient("1 стакан молока")

print(result)

ValidationError: 3 validation errors for ParsedIngredient
ingredient
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/string_type
quantity
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
unit
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/string_type

In [5]:
find_text

' стакан молока'

In [18]:
import time 
import asyncio

from fastapi import FastAPI, BackgroundTasks

app = FastAPI()

def sync_task():
    time.sleep(3)
    print('Load.')

async def async_task():
    await asyncio.sleep(3)
    print('Сделаем запрос.')


@app.post('/')
async def some_route(bg_tasks : BackgroundTasks):
    # task = asyncio.create_task(async_task())
    bg_tasks.add_task(sync_task)
    return {'ok' : True}

In [113]:
a = [100,4,200,1,3,2]
a.sort()

In [114]:
a

[1, 2, 3, 4, 100, 200]

In [126]:
def subarray_sum(nums, k):
    prefix_count = {0 : 1}
    curr_sum = 0
    count = 0

    for num in nums:
        curr_sum += num 
        need = curr_sum - k

        if need in prefix_count:
            count += prefix_count[need]

        prefix_count[curr_sum] = prefix_count.get(curr_sum, 0) + 1

    return count


print(subarray_sum([1,1,1], 2))      # 2
print(subarray_sum([1,2,3], 3))      # 2
print(subarray_sum([1,-1,0], 0))     # 3

2
2
3

In [137]:
def productofarrayacceptself(nums):
    n = len(nums)
    answer = [1] * n
    
    prefix = 1 
    for i in range(n):
        answer[i] = prefix
        prefix *= nums[i]

    suffix = 1 
    for i in range(n - 1, -1, -1):
        answer[i] *= suffix
        suffix *= nums[i]

    
    return answer


productofarrayacceptself([1,2,3,4])

[24, 12, 8, 6]

In [ ]:
from collections import Counter 

def is_anagram(s: str, t: str) -> bool:
    return Counter(s) == Counter(t)



# Примеры:
print(is_anagram("anagram", "nagaram"))  # True
print(is_anagram("rat", "car"))          # False
print(is_anagram("aacc", "ccac"))        # False

True
False
False

In [142]:
def max_profit(prices: list[int]) -> int:
    min_price = float('inf')
    max_profit = 0

    for price in prices:
        min_price = min(min_price, price)
        profit = price - min_price
        max_profit = max(max_profit, profit)

    return max_profit


# Примеры:
print(max_profit([7,1,5,3,6,4]))  # 5
print(max_profit([7,6,4,3,1]))    # 0

5
0

In [145]:
def move_zeroes(nums: list[int]) -> list[int]:
    left = 0 

    for right in range(len(nums)):
        if nums[right] != 0:
            nums[left], nums[right] = nums[right], nums[left]
            left += 1

    return nums


# Примеры:
print(move_zeroes([0,1,0,3,12]))
print(move_zeroes([0]))
print(move_zeroes([1,2,3]))

[1, 3, 12, 0, 0]
[0]
[1, 2, 3]

In [155]:
def transaction_stats(transactions):

    hashmap = {}

    for transaction in transactions:
        user_id = transaction['user_id']
        amount = transaction['amount']

        if user_id not in hashmap:
            hashmap[user_id] = {
                'count': 0,
                'total': 0
            }

        hashmap[user_id]['count'] += 1
        hashmap[user_id]['total'] += amount


    for user_id in hashmap:
        total = hashmap[user_id]['total']
        count = hashmap[user_id]['count']

        hashmap[user_id]['avg'] = total / count

    return hashmap


transactions = [
    {"user_id": 1, "amount": 100},
    {"user_id": 2, "amount": 50},
    {"user_id": 1, "amount": 200},
    {"user_id": 3, "amount": 70},
    {"user_id": 2, "amount": 30},
]

print(transaction_stats(transactions))

{1: {'count': 2, 'total': 300, 'avg': 150.0}, 2: {'count': 2, 'total': 80, 'avg': 40.0}, 3: {'count': 1, 'total': 70, 'avg': 70.0}}

In [1]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F
import os

#os.environ["PYSPARK_PYTHON"] = "/usr/bin/python3"

spark = (
    SparkSession.builder
    .appName("light-cluster-test")
    .master("spark://10.55.6.41:7077")
    .config("spark.driver.host", "10.20.0.100")
    .config("spark.driver.bindAddress", "0.0.0.0")
    .getOrCreate()
)

In [2]:
import pandas as pd

In [3]:
path = r"C:/Users/46120/Desktop/sales.csv"

In [4]:
df = pd.read_csv(path)

In [5]:
data = spark.createDataFrame(df)

In [6]:
data.show()

+---+------+-------+------+
| id|  city|product| price|
+---+------+-------+------+
|  1|Moscow|  Phone| 50000|
|  2|   SPB| Laptop|100000|
|  3|Moscow|  Phone| 52000|
|  4| Kazan|     TV| 30000|
|  5|   SPB|  Phone| 51000|
|  6|Moscow| Laptop|110000|
|  7| Kazan|  Phone| 49000|
|  8|Moscow|     TV| 35000|
|  9|   SPB|     TV| 32000|
| 10|Moscow|  Phone| 53000|
| 11| Kazan| Laptop|105000|
| 12|   SPB|  Phone| 50000|
| 13|Moscow| Laptop|115000|
| 14| Kazan|     TV| 31000|
| 15|   SPB| Laptop| 99000|
| 16|Moscow|  Phone| 55000|
| 17| Kazan|  Phone| 48000|
| 18|   SPB|     TV| 33000|
| 19|Moscow| Laptop|120000|
| 20| Kazan|  Phone| 50000|
+---+------+-------+------+

In [20]:
data\
    .groupBy('city')\
    .agg(
        F.count('price').alias('count'),
        F.avg('price').alias('avg_price'),
        F.max('price').alias('max_price'),
        F.min('price').alias('min_price')
              )\
    .explain(True)
    #.show()

== Parsed Logical Plan ==
'Aggregate ['city], ['city, 'count('price) AS count#112, 'avg('price) AS avg_price#113, 'max('price) AS max_price#114, 'min('price) AS min_price#115]
+- LogicalRDD [id#0L, city#1, product#2, price#3L], false

== Analyzed Logical Plan ==
city: string, count: bigint, avg_price: double, max_price: bigint, min_price: bigint
Aggregate [city#1], [city#1, count(price#3L) AS count#112L, avg(price#3L) AS avg_price#113, max(price#3L) AS max_price#114L, min(price#3L) AS min_price#115L]
+- LogicalRDD [id#0L, city#1, product#2, price#3L], false

== Optimized Logical Plan ==
Aggregate [city#1], [city#1, count(price#3L) AS count#112L, avg(price#3L) AS avg_price#113, max(price#3L) AS max_price#114L, min(price#3L) AS min_price#115L]
+- Project [city#1, price#3L]
   +- LogicalRDD [id#0L, city#1, product#2, price#3L], false

== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- HashAggregate(keys=[city#1], functions=[count(price#3L), avg(price#3L), max(price#3L), min(price#3L)], output=[city#1, count#112L, avg_price#113, max_price#114L, min_price#115L])
   +- Exchange hashpartitioning(city#1, 200), ENSURE_REQUIREMENTS, [plan_id=204]
      +- HashAggregate(keys=[city#1], functions=[partial_count(price#3L), partial_avg(price#3L), partial_max(price#3L), partial_min(price#3L)], output=[city#1, count#129L, sum#130, count#131L, max#132L, min#133L])
         +- Project [city#1, price#3L]
            +- Scan ExistingRDD[id#0L,city#1,product#2,price#3L]

In [7]:
data.show()

+---+------+-------+------+
| id|  city|product| price|
+---+------+-------+------+
|  1|Moscow|  Phone| 50000|
|  2|   SPB| Laptop|100000|
|  3|Moscow|  Phone| 52000|
|  4| Kazan|     TV| 30000|
|  5|   SPB|  Phone| 51000|
|  6|Moscow| Laptop|110000|
|  7| Kazan|  Phone| 49000|
|  8|Moscow|     TV| 35000|
|  9|   SPB|     TV| 32000|
| 10|Moscow|  Phone| 53000|
| 11| Kazan| Laptop|105000|
| 12|   SPB|  Phone| 50000|
| 13|Moscow| Laptop|115000|
| 14| Kazan|     TV| 31000|
| 15|   SPB| Laptop| 99000|
| 16|Moscow|  Phone| 55000|
| 17| Kazan|  Phone| 48000|
| 18|   SPB|     TV| 33000|
| 19|Moscow| Laptop|120000|
| 20| Kazan|  Phone| 50000|
+---+------+-------+------+

In [6]:
cities = [
    ("Moscow", "Center"),
    ("SPB", "North-West"),
    ("Kazan", "Volga")
]

In [7]:
cities = (
    cities
    .withColumnRenamed("_1", "city")
    .withColumnRenamed("_2", "region")
)

AttributeError: 'list' object has no attribute 'withColumnRenamed'

In [8]:
cities = spark.createDataFrame(cities, ['city', 'region'])

In [8]:
data.show()

+---+------+-------+------+
| id|  city|product| price|
+---+------+-------+------+
|  1|Moscow|  Phone| 50000|
|  2|   SPB| Laptop|100000|
|  3|Moscow|  Phone| 52000|
|  4| Kazan|     TV| 30000|
|  5|   SPB|  Phone| 51000|
|  6|Moscow| Laptop|110000|
|  7| Kazan|  Phone| 49000|
|  8|Moscow|     TV| 35000|
|  9|   SPB|     TV| 32000|
| 10|Moscow|  Phone| 53000|
| 11| Kazan| Laptop|105000|
| 12|   SPB|  Phone| 50000|
| 13|Moscow| Laptop|115000|
| 14| Kazan|     TV| 31000|
| 15|   SPB| Laptop| 99000|
| 16|Moscow|  Phone| 55000|
| 17| Kazan|  Phone| 48000|
| 18|   SPB|     TV| 33000|
| 19|Moscow| Laptop|120000|
| 20| Kazan|  Phone| 50000|
+---+------+-------+------+

In [9]:
cities.show()

+------+----------+
|  city|    region|
+------+----------+
|Moscow|    Center|
|   SPB|North-West|
| Kazan|     Volga|
+------+----------+

In [20]:
group_city = data\
    .groupBy("city").agg(F.max("price").alias("max_price"))

In [21]:
group_city.show()

+------+---------+
|  city|max_price|
+------+---------+
|Moscow|   120000|
|   SPB|   100000|
| Kazan|   105000|
+------+---------+

In [22]:
join_data = group_city.join(cities, group_city.city == cities.city, 'left')

In [27]:
join_data = group_city\
    .join(F.broadcast(cities), on="city", how="left")

In [28]:
join_data.show()

+------+---------+----------+
|  city|max_price|    region|
+------+---------+----------+
|Moscow|   120000|    Center|
| Kazan|   105000|     Volga|
|   SPB|   100000|North-West|
+------+---------+----------+

In [29]:
join_data.explain(True)

== Parsed Logical Plan ==
'Join UsingJoin(LeftOuter, [city])
:- Aggregate [city#1], [city#1, max(price#3L) AS max_price#41L]
:  +- LogicalRDD [id#0L, city#1, product#2, price#3L], false
+- ResolvedHint (strategy=broadcast)
   +- Project [city#26, _2#5 AS region#27]
      +- Project [_1#4 AS city#26, _2#5]
         +- LogicalRDD [_1#4, _2#5], false

== Analyzed Logical Plan ==
city: string, max_price: bigint, region: string
Project [city#1, max_price#41L, region#27]
+- Join LeftOuter, (city#1 = city#26)
   :- Aggregate [city#1], [city#1, max(price#3L) AS max_price#41L]
   :  +- LogicalRDD [id#0L, city#1, product#2, price#3L], false
   +- ResolvedHint (strategy=broadcast)
      +- Project [city#26, _2#5 AS region#27]
         +- Project [_1#4 AS city#26, _2#5]
            +- LogicalRDD [_1#4, _2#5], false

== Optimized Logical Plan ==
Project [city#1, max_price#41L, region#27]
+- Join LeftOuter, (city#1 = city#26), rightHint=(strategy=broadcast)
   :- Aggregate [city#1], [city#1, max(price#3L) AS max_price#41L]
   :  +- Project [city#1, price#3L]
   :     +- LogicalRDD [id#0L, city#1, product#2, price#3L], false
   +- Project [_1#4 AS city#26, _2#5 AS region#27]
      +- Filter isnotnull(_1#4)
         +- LogicalRDD [_1#4, _2#5], false

== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- Project [city#1, max_price#41L, region#27]
   +- BroadcastHashJoin [city#1], [city#26], LeftOuter, BuildRight, false
      :- HashAggregate(keys=[city#1], functions=[max(price#3L)], output=[city#1, max_price#41L])
      :  +- Exchange hashpartitioning(city#1, 200), ENSURE_REQUIREMENTS, [plan_id=588]
      :     +- HashAggregate(keys=[city#1], functions=[partial_max(price#3L)], output=[city#1, max#50L])
      :        +- Project [city#1, price#3L]
      :           +- Scan ExistingRDD[id#0L,city#1,product#2,price#3L]
      +- BroadcastExchange HashedRelationBroadcastMode(List(input[0, string, true]),false), [plan_id=591]
         +- Project [_1#4 AS city#26, _2#5 AS region#27]
            +- Filter isnotnull(_1#4)
               +- Scan ExistingRDD[_1#4,_2#5]

In [8]:
moscow_city = data\
        .where(F.col('city') == 'Moscow')\
        .where(F.col('price') > 51000)\

In [10]:
moscow_city.show()

+---+------+-------+------+
| id|  city|product| price|
+---+------+-------+------+
|  3|Moscow|  Phone| 52000|
|  6|Moscow| Laptop|110000|
| 10|Moscow|  Phone| 53000|
| 13|Moscow| Laptop|115000|
| 16|Moscow|  Phone| 55000|
| 19|Moscow| Laptop|120000|
+---+------+-------+------+

In [11]:
moscow_city.printSchema()

root
 |-- id: long (nullable = true)
 |-- city: string (nullable = true)
 |-- product: string (nullable = true)
 |-- price: long (nullable = true)

In [15]:
moscow_city\
    .coalesce(1)\
    .write\
    .format('csv')\
    .options(header=True, sep=';')\
    .csv(r"C:/Users/46120/Desktop")

AnalysisException: [PATH_ALREADY_EXISTS] Path file:/C:/Users/46120/Desktop already exists. Set mode as "overwrite" to overwrite the existing path. SQLSTATE: 42K04

In [14]:
print(moscow_city.rdd.getNumPartitions())

2

In [31]:
data.cache().count()

20

In [32]:
data.unpersist()

DataFrame[id: bigint, city: string, product: string, price: bigint]

In [33]:
from pyspark.storagelevel import StorageLevel
data.persist(StorageLevel.DISK_ONLY).count()

20

In [10]:
data.createOrReplaceTempView("sales")
cities.createOrReplaceTempView("cities")

In [12]:
spark.sql("""SELECT s.city,
                    c.region,
                    COUNT(s.price) as count_price,
                    AVG(s.price) as avg_price,
                    MAX(s.price) as max_price
          FROM sales AS s
          LEFT JOIN cities AS c ON s.city = c.city 
          GROUP BY
                s.city,
                c.region
          """).show()

+------+----------+-----------+------------------+---------+
|  city|    region|count_price|         avg_price|max_price|
+------+----------+-----------+------------------+---------+
|   SPB|North-West|          6|60833.333333333336|   100000|
| Kazan|     Volga|          6|52166.666666666664|   105000|
|Moscow|    Center|          8|           73750.0|   120000|
+------+----------+-----------+------------------+---------+

In [13]:
def is_palindrome(s: str) -> bool:
    s = ''.join(c.lower() for c in s if c.isalnum())

    left, right = 0, len(s) - 1

    while left < right:
        if s[left] == s[right]:
            left += 1
            right -= 1
        else:
            return False
        
    return True


print(is_palindrome("A man, a plan, a canal: Panama"))  # True
print(is_palindrome("race a car"))                      # False
print(is_palindrome(" "))                               # True
print(is_palindrome("0P"))                              # False

True
False
True
False

In [16]:
from typing import List

def two_sum_sorted(numbers: List[int], target: int) -> List[int]:
    left, right = 0, len(numbers) - 1

    while left < right:  
        if numbers[left] + numbers[right] == target:
            return [left + 1, right + 1] 
        elif numbers[left] + numbers[right] < target:
            left += 1
        else: 
            right -= 1

    #return 

# Тесты:
print(two_sum_sorted([2,7,11,15], 9))           # [1,2]
print(two_sum_sorted([1,2,3,4,4,9,56,90], 8))   # [4,5]
print(two_sum_sorted([1,3,4,5,6], 10))          # [4,5]

[1, 2]
[4, 5]
[3, 5]

In [17]:
def length_of_longest_substring(s: str) -> int:
    left = 0 
    unique_char = set()
    max_length = 0 

    for right in range(len(s)):
        while s[right] in unique_char:
            unique_char.remove(s[left])
            left += 1
        unique_char.add(s[right])
        max_length = max(max_length, right - left + 1)
        
    return max_length
        


# Примеры:
print(length_of_longest_substring("abcabcbb"))  # 3 ("abc")
print(length_of_longest_substring("bbbbb"))     # 1 ("b")
print(length_of_longest_substring("pwwkew"))    # 3 ("wke")
print(length_of_longest_substring(""))          # 0

3
1
3
0

In [19]:
from typing import List

def min_subarray_len(target: int, nums: List[int]) -> int:
    left = 0
    min_lenght = float('inf')
    sum_nums = 0

    for right in range(len(nums)):
        sum_nums += nums[right]

        while sum_nums >= target:
            min_lenght = min(min_lenght, right - left + 1)
            sum_nums -= nums[left]
            left += 1
            
    if min_lenght == float('inf'):
        return 0
                           
    return min_lenght 
        



print(min_subarray_len(7, [2,3,1,2,4,3]))  # 2
print(min_subarray_len(4, [1,4,4]))        # 1
print(min_subarray_len(11, [1,1,1,1,1]))   # 0

2
1
0

In [25]:
def check_inclusion(s1: str, s2: str) -> bool:
    if len(s1) > len(s2):
        return False
    
    s1_count = {}
    s2_count = {}

    for i in range(len(s1)):
        s1_count[s1[i]] = 1 + s1_count.get(s1[i], 0)
        s2_count[s2[i]] = 1 + s2_count.get(s2[i], 0)

    if s1_count == s2_count:
        return True
    
    left = 0
    for right in range(len(s1), len(s2)):
        s2_count[s2[right]] = 1 + s2_count.get(s2[right], 0)
        s2_count[s2[left]] -= 1

        if s2_count[s2[left]] == 0:
            del s2_count[s2[left]]

        left += 1

        if s1_count == s2_count:
            return True
        
    return False



print(check_inclusion("ab", "eidbaooo"))  # True
print(check_inclusion("ab", "eidboaoo"))  # False

True
False

In [33]:
from typing import List
from collections import defaultdict

def group_anagrams(strs: List[str]) -> List[List[str]]:
    hashmap = {}

    for word in strs:
        key = ''.join(sorted(word))
        if key not in hashmap:
            hashmap[key] = []
        hashmap[key].append(word)

    return list(hashmap.values())

print(group_anagrams(["eat","tea","tan","ate","nat","bat"]))
print(group_anagrams([""]))
print(group_anagrams(["a"]))

[['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]
[['']]
[['a']]

In [38]:
from typing import List

def contains_duplicate(nums: List[int]) -> bool:
    hashmap = {}

    for num in nums:
        if num in hashmap:
            hashmap[num] += 1
        else:
            hashmap[num] = 1
    
    for key, value in hashmap.items():
        if value > 1:
            return True
        
    return False


print(contains_duplicate([1,2,3,1]))     # True
print(contains_duplicate([1,2,3,4]))     # False
print(contains_duplicate([1,1,1,3,3,4])) # True

True
False
True

In [58]:
from typing import List

def top_k_frequent(nums: List[int], k: int) -> List[int]:
    hashmap = {}

    for num in nums:
        if num in hashmap:
            hashmap[num] += 1 
        else:
            hashmap[num] = 1 

    sorted_hashmap = dict(sorted(hashmap.items(), key=lambda iter_ : iter_[1], reverse=True))

    result = []

    for key in sorted_hashmap:
        result.append(key)

    return result[:k]


print(top_k_frequent([1,1,1,2,2,3], 2))
print(top_k_frequent([1], 1))

[1, 2]
[1]

In [59]:
from typing import List

def subarray_sum(nums: List[int], k: int) -> int:
    prefix_count = {0 : 1}
    curr_sum = 0 
    count = 0

    for num in nums:
        curr_sum += num
        need = curr_sum - k 
        if need in prefix_count: 
            count += prefix_count[need]

        prefix_count[curr_sum] = prefix_count.get(curr_sum, 0) + 1

    return count


            


print(subarray_sum([1,1,1], 2))     # 2
print(subarray_sum([1,2,3], 3))     # 2
print(subarray_sum([1,-1,0], 0))    # 3

2
2
3

In [63]:
from typing import List

def search_insert(nums: List[int], target: int) -> int:
    left, right = 0, len(nums) - 1

    while left <= right:
        mid = (left + right) // 2
        if nums[mid] == target:
            return mid
        elif nums[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return left 

print(search_insert([1,3,5,6], 5))  # 2
print(search_insert([1,3,5,6], 2))  # 1
print(search_insert([1,3,5,6], 7))  # 4
print(search_insert([1,3,5,6], 0))  # 0

2
1
4
0

In [ ]:
from typing import List

def search_range(nums: List[int], target: int) -> List[int]:
    def find_left():
        left, right = 0, len(nums) - 1
        index = -1
        while left <= right:
            mid = (left + right) // 2
            if nums[mid] == target:
                index = mid
                right = mid - 1  # продолжаем искать слева
            elif nums[mid] < target:
                left = mid + 1
            else:
                right = mid - 1
        return index

    def find_right():
        left, right = 0, len(nums) - 1
        index = -1
        while left <= right:
            mid = (left + right) // 2
            if nums[mid] == target:
                index = mid
                left = mid + 1  # продолжаем искать слева
            elif nums[mid] < target:
                left = mid + 1
            else:
                right = mid - 1
        return index

    return [find_left(), find_right()]

print(search_range([5,7,7,8,8,10], 8))
print(search_range([5,7,7,8,8,10], 6))
print(search_range([], 0))

[3, 4]
[-1, -1]
[-1, -1]

:

In [25]:
filter_data